// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Assets defines model for assets.
type Assets struct {
	DefaultImageUrl *string `json:"default_image_url,omitempty"`
}

// Factsheet defines model for factsheet.
type Factsheet struct {
	Assets       Assets             `json:"assets"`
	Id           openapi_types.UUID `json:"id"`
	Requirements Requirements       `json:"requirements"`
	Taxonomy     Taxonomy           `json:"taxonomy"`
}

// Plant defines model for plant.
type Plant struct {
	Assets   Assets             `json:"assets"`
	Id       openapi_types.UUID `json:"id"`
	Taxonomy Taxonomy           `json:"taxonomy"`
}

// Requirement defines model for requirement.
type Requirement struct {
	Max  float64 `json:"max"`
	Min  float64 `json:"min"`
	Unit string  `json:"unit"`
}

// Requirements defines model for requirements.
type Requirements struct {
	LightIntensity Requirement `json:"light_intensity"`
	SoilMoisture   Requirement `json:"soil_moisture"`
	Temperature    Requirement `json:"temperature"`
}

// SearchRequest defines model for search_request.
type SearchRequest struct {
	Name *string `json:"name,omitempty"`
}

// Taxonomy defines model for taxonomy.
type Taxonomy struct {
	CommonName     string `json:"common_name"`
	ScientificName string `json:"scientific_name"`
}

// PostSearchJSONRequestBody defines body for PostSearch for application/json ContentType.
type PostSearchJSONRequestBody = SearchRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /search)
	PostSearch(w http.ResponseWriter, r *http.Request)

	// (GET /species)
	GetSpecies(w http.ResponseWriter, r *http.Request)

	// (GET /species/{id})
	GetSpeciesId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /species/{id}/requirements)
	GetSpeciesIdRequirements(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /species/{id}/taxonomy)
	GetSpeciesIdTaxonomy(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /search)
func (_ Unimplemented) PostSearch(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /species)
func (_ Unimplemented) GetSpecies(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /species/{id})
func (_ Unimplemented) GetSpeciesId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /species/{id}/requirements)
func (_ Unimplemented) GetSpeciesIdRequirements(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /species/{id}/taxonomy)
func (_ Unimplemented) GetSpeciesIdTaxonomy(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostSearch operation middleware
func (siw *ServerInterfaceWrapper) PostSearch(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSearch(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetSpecies operation middleware
func (siw *ServerInterfaceWrapper) GetSpecies(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSpecies(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetSpeciesId operation middleware
func (siw *ServerInterfaceWrapper) GetSpeciesId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSpeciesId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetSpeciesIdRequirements operation middleware
func (siw *ServerInterfaceWrapper) GetSpeciesIdRequirements(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSpeciesIdRequirements(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetSpeciesIdTaxonomy operation middleware
func (siw *ServerInterfaceWrapper) GetSpeciesIdTaxonomy(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSpeciesIdTaxonomy(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/search", wrapper.PostSearch)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/species", wrapper.GetSpecies)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/species/{id}", wrapper.GetSpeciesId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/species/{id}/requirements", wrapper.GetSpeciesIdRequirements)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/species/{id}/taxonomy", wrapper.GetSpeciesIdTaxonomy)
	})

	return r
}

type PostSearchRequestObject struct {
	Body *PostSearchJSONRequestBody
}

type PostSearchResponseObject interface {
	VisitPostSearchResponse(w http.ResponseWriter) error
}

type PostSearch200JSONResponse []Plant

func (response PostSearch200JSONResponse) VisitPostSearchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostSearch400Response struct {
}

func (response PostSearch400Response) VisitPostSearchResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PostSearch500Response struct {
}

func (response PostSearch500Response) VisitPostSearchResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetSpeciesRequestObject struct {
}

type GetSpeciesResponseObject interface {
	VisitGetSpeciesResponse(w http.ResponseWriter) error
}

type GetSpecies200JSONResponse []Plant

func (response GetSpecies200JSONResponse) VisitGetSpeciesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSpecies500Response struct {
}

func (response GetSpecies500Response) VisitGetSpeciesResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetSpeciesIdRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetSpeciesIdResponseObject interface {
	VisitGetSpeciesIdResponse(w http.ResponseWriter) error
}

type GetSpeciesId200JSONResponse Factsheet

func (response GetSpeciesId200JSONResponse) VisitGetSpeciesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSpeciesId404Response struct {
}

func (response GetSpeciesId404Response) VisitGetSpeciesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetSpeciesId500Response struct {
}

func (response GetSpeciesId500Response) VisitGetSpeciesIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetSpeciesIdRequirementsRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetSpeciesIdRequirementsResponseObject interface {
	VisitGetSpeciesIdRequirementsResponse(w http.ResponseWriter) error
}

type GetSpeciesIdRequirements200JSONResponse Requirements

func (response GetSpeciesIdRequirements200JSONResponse) VisitGetSpeciesIdRequirementsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSpeciesIdRequirements404Response struct {
}

func (response GetSpeciesIdRequirements404Response) VisitGetSpeciesIdRequirementsResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetSpeciesIdRequirements500Response struct {
}

func (response GetSpeciesIdRequirements500Response) VisitGetSpeciesIdRequirementsResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetSpeciesIdTaxonomyRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetSpeciesIdTaxonomyResponseObject interface {
	VisitGetSpeciesIdTaxonomyResponse(w http.ResponseWriter) error
}

type GetSpeciesIdTaxonomy200JSONResponse Taxonomy

func (response GetSpeciesIdTaxonomy200JSONResponse) VisitGetSpeciesIdTaxonomyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSpeciesIdTaxonomy404Response struct {
}

func (response GetSpeciesIdTaxonomy404Response) VisitGetSpeciesIdTaxonomyResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetSpeciesIdTaxonomy500Response struct {
}

func (response GetSpeciesIdTaxonomy500Response) VisitGetSpeciesIdTaxonomyResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /search)
	PostSearch(ctx context.Context, request PostSearchRequestObject) (PostSearchResponseObject, error)

	// (GET /species)
	GetSpecies(ctx context.Context, request GetSpeciesRequestObject) (GetSpeciesResponseObject, error)

	// (GET /species/{id})
	GetSpeciesId(ctx context.Context, request GetSpeciesIdRequestObject) (GetSpeciesIdResponseObject, error)

	// (GET /species/{id}/requirements)
	GetSpeciesIdRequirements(ctx context.Context, request GetSpeciesIdRequirementsRequestObject) (GetSpeciesIdRequirementsResponseObject, error)

	// (GET /species/{id}/taxonomy)
	GetSpeciesIdTaxonomy(ctx context.Context, request GetSpeciesIdTaxonomyRequestObject) (GetSpeciesIdTaxonomyResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostSearch operation middleware
func (sh *strictHandler) PostSearch(w http.ResponseWriter, r *http.Request) {
	var request PostSearchRequestObject

	var body PostSearchJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostSearch(ctx, request.(PostSearchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSearch")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostSearchResponseObject); ok {
		if err := validResponse.VisitPostSearchResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSpecies operation middleware
func (sh *strictHandler) GetSpecies(w http.ResponseWriter, r *http.Request) {
	var request GetSpeciesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSpecies(ctx, request.(GetSpeciesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSpecies")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSpeciesResponseObject); ok {
		if err := validResponse.VisitGetSpeciesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSpeciesId operation middleware
func (sh *strictHandler) GetSpeciesId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetSpeciesIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSpeciesId(ctx, request.(GetSpeciesIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSpeciesId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSpeciesIdResponseObject); ok {
		if err := validResponse.VisitGetSpeciesIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSpeciesIdRequirements operation middleware
func (sh *strictHandler) GetSpeciesIdRequirements(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetSpeciesIdRequirementsRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSpeciesIdRequirements(ctx, request.(GetSpeciesIdRequirementsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSpeciesIdRequirements")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSpeciesIdRequirementsResponseObject); ok {
		if err := validResponse.VisitGetSpeciesIdRequirementsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSpeciesIdTaxonomy operation middleware
func (sh *strictHandler) GetSpeciesIdTaxonomy(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetSpeciesIdTaxonomyRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSpeciesIdTaxonomy(ctx, request.(GetSpeciesIdTaxonomyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSpeciesIdTaxonomy")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSpeciesIdTaxonomyResponseObject); ok {
		if err := validResponse.VisitGetSpeciesIdTaxonomyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xWTW8TMRD9K6uB4zYboFz2WCGhCAkQ5VZFkbs7SQatP2rPVo0q/3dkO+1+JG0aoAVx",
	"2495M++9sT2+hUpLoxUqdlDegqvWKEV8FM5h+misNmiZML7VuBRtwwuSYoWL1jbhI28MQgmOLakVeO9z",
	"WIqK3RqRd1N0qV9bXEIJr4qORrHlUGyjfA5Uh9iltlIwlNC2VEM+rpmDxauWLMo7MY8lH8T6HFjcaKXl",
	"5hDuPs53BWsoLyBRuvs7IpPfSZ77HEwj1MuZ8seF9ZT0NO7qkeJmQLDW7WWDHUXVyku0gaIk9cTIVhHv",
	"W25DxiFfHutvEfM9i2NItqHVmhekGJUj3hyxegItp6lZSE2OW4tHYhmlQSuORo4099OMCeU78oIhDoWt",
	"1ouQBN2e/ikh8YGt3V9TQ1ClpdRq8QA2B1cRKqYlVQ/FjHT1E+7C55EOqaWOmYibkOpr2GBZPH8yh/aa",
	"qoC9RutIKyhhOnkzmQY22qAShqCEd5PpZAo5GMHrKKRI9kSFOtmjo8Gk1awORbTj8xSTGKPjM11vkgvB",
	"6QgSxjRURVjxw2nVHbKHuj3qj/fJGme0csnst9PpUdWIUR48YNLp5O83n7BWbFLba3SVJcPJxS+fQtRp",
	"4jD8dSbqbMs7O8lIXYuG6uyqRbsJmPf7MDPFaJVoYsfQZmittlvVhTNYbVfYCvc04yPy+TbkH/Tol/UW",
	"t1T7J4ie1b8r+zG13SB/ZBWc7ir8rDlb6lbVx3sQNqIVEhmtg/JijIv+Z7MPEPZ+eBccdmE6UdLA6s4Q",
	"ti3mPakHJqafjxtQjEfHwW58G87+Z+vM8BLz15rzEj3oj5yD/n/vX8Oeyfvefel/8j1eDELdVCJe7+9b",
	"cVJfgp/7nwEAAP//D5KoDDUMAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
