services:
  traefik: 
    image: traefik:v3.3.2
    depends_on:
      - user-data-store
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.grpcweb.address=:50052"
    ports:
      - "80:80"
      - "50052:50052"
      # - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  monitoring-agent:
    ports: 
      - "50051:50051"
    image: cosmtrek/air:v1.61.1
    working_dir: /app
    depends_on:
      - redis
    volumes:
      - ./monitoring-agent-go/:/app/
      # - ./mock-monitoring-agent/:/app/
    environment:
      - REDIS_ADDRESS=redis:6379
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitoring-agent.rule=HostRegexp(`.*`)"
      - "traefik.http.services.monitoring-agent.loadbalancer.server.scheme=h2c"
      - "traefik.http.services.monitoring-agent.loadbalancer.server.port=50051"
      - "traefik.http.routers.monitoring-agent.entrypoints=grpcweb"
      - "traefik.http.middlewares.mar-grpcweb.grpcweb.allowOrigins=*"
      - "traefik.http.routers.monitoring-agent.middlewares=mar-grpcweb"
  user-data-store:
    image: cosmtrek/air:v1.61.1
    working_dir: /app
    volumes:
      - ./user-data/:/app/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user-data.rule=Host(`localhost`)"
      - "traefik.http.routers.user-data.rule=PathPrefix(`/user-data`)"
      - "traefik.http.services.user-data.loadbalancer.server.port=9090"
      - "traefik.http.routers.user-data.entrypoints=web"
  species-catalog:
    image: cosmtrek/air:v1.61.1
    working_dir: /app
    volumes:
      - ./species-catalog/:/app/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.species-catalog.rule=Host(`localhost`)"
      - "traefik.http.routers.species-catalog.rule=PathPrefix(`/species-catalog`)"
      - "traefik.http.services.species-catalog.loadbalancer.server.port=8080"
      - "traefik.http.routers.species-catalog.entrypoints=web"
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - USER_DATA_STORE_BASE_PATH=/user-data
        - SPECIES_CATALOG_BASE_PATH=/species-catalog
        - MONITORING_AGENT_GRPC_HOST=localhost
        - MONITORING_AGENT_GRPC_PORT=50052
    depends_on:
      - monitoring-agent
      - user-data-store
      - species-catalog
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      - "traefik.http.routers.app.rule=PathPrefix(`/`)"
      - "traefik.http.services.app.loadbalancer.server.port=80"
      - "traefik.http.routers.app.entrypoints=web"
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server
    ports:
      - "6379:6379"
      - "8001:8001" # RedisInsight UI
    volumes:
      - redis_data:/data
      - ./redis.conf:/redis-stack.conf
volumes:
  redis_data:
    driver: local
