// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Garden defines model for garden.
type Garden struct {
	Id       openapi_types.UUID `json:"id"`
	ImageUrl *string            `json:"image_url,omitempty"`
	Name     string             `json:"name"`
}

// GardenCreate defines model for garden_create.
type GardenCreate struct {
	Name string `json:"name"`
}

// Plant defines model for plant.
type Plant struct {
	FactsheetId openapi_types.UUID `json:"factsheet_id"`
	Id          openapi_types.UUID `json:"id"`
	ImageUrl    *string            `json:"image_url,omitempty"`
	Name        string             `json:"name"`
}

// PlantCreate defines model for plant_create.
type PlantCreate struct {
	FactsheetId openapi_types.UUID `json:"factsheet_id"`
	ImageUrl    *string            `json:"image_url,omitempty"`
	Name        string             `json:"name"`
}

// Sensors defines model for sensors.
type Sensors map[string]string

// PostGardensJSONRequestBody defines body for PostGardens for application/json ContentType.
type PostGardensJSONRequestBody = GardenCreate

// PostGardensIdPlantsJSONRequestBody defines body for PostGardensIdPlants for application/json ContentType.
type PostGardensIdPlantsJSONRequestBody = PlantCreate

// PatchGardensIdSensorsJSONRequestBody defines body for PatchGardensIdSensors for application/json ContentType.
type PatchGardensIdSensorsJSONRequestBody = Sensors

// PutPlantsIdJSONRequestBody defines body for PutPlantsId for application/json ContentType.
type PutPlantsIdJSONRequestBody = PlantCreate

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /gardens)
	GetGardens(w http.ResponseWriter, r *http.Request)

	// (POST /gardens)
	PostGardens(w http.ResponseWriter, r *http.Request)

	// (GET /gardens/{id}/plants)
	GetGardensIdPlants(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (POST /gardens/{id}/plants)
	PostGardensIdPlants(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /gardens/{id}/sensors)
	GetGardensIdSensors(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PATCH /gardens/{id}/sensors)
	PatchGardensIdSensors(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (GET /plants/{id})
	GetPlantsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)

	// (PUT /plants/{id})
	PutPlantsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /gardens)
func (_ Unimplemented) GetGardens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /gardens)
func (_ Unimplemented) PostGardens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /gardens/{id}/plants)
func (_ Unimplemented) GetGardensIdPlants(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /gardens/{id}/plants)
func (_ Unimplemented) PostGardensIdPlants(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /gardens/{id}/sensors)
func (_ Unimplemented) GetGardensIdSensors(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /gardens/{id}/sensors)
func (_ Unimplemented) PatchGardensIdSensors(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /plants/{id})
func (_ Unimplemented) GetPlantsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /plants/{id})
func (_ Unimplemented) PutPlantsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetGardens operation middleware
func (siw *ServerInterfaceWrapper) GetGardens(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGardens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostGardens operation middleware
func (siw *ServerInterfaceWrapper) PostGardens(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostGardens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGardensIdPlants operation middleware
func (siw *ServerInterfaceWrapper) GetGardensIdPlants(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGardensIdPlants(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostGardensIdPlants operation middleware
func (siw *ServerInterfaceWrapper) PostGardensIdPlants(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostGardensIdPlants(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGardensIdSensors operation middleware
func (siw *ServerInterfaceWrapper) GetGardensIdSensors(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGardensIdSensors(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchGardensIdSensors operation middleware
func (siw *ServerInterfaceWrapper) PatchGardensIdSensors(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchGardensIdSensors(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlantsId operation middleware
func (siw *ServerInterfaceWrapper) GetPlantsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlantsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutPlantsId operation middleware
func (siw *ServerInterfaceWrapper) PutPlantsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutPlantsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/gardens", wrapper.GetGardens)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/gardens", wrapper.PostGardens)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/gardens/{id}/plants", wrapper.GetGardensIdPlants)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/gardens/{id}/plants", wrapper.PostGardensIdPlants)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/gardens/{id}/sensors", wrapper.GetGardensIdSensors)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/gardens/{id}/sensors", wrapper.PatchGardensIdSensors)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/plants/{id}", wrapper.GetPlantsId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/plants/{id}", wrapper.PutPlantsId)
	})

	return r
}

type GetGardensRequestObject struct {
}

type GetGardensResponseObject interface {
	VisitGetGardensResponse(w http.ResponseWriter) error
}

type GetGardens200JSONResponse []Garden

func (response GetGardens200JSONResponse) VisitGetGardensResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGardens500Response struct {
}

func (response GetGardens500Response) VisitGetGardensResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PostGardensRequestObject struct {
	Body *PostGardensJSONRequestBody
}

type PostGardensResponseObject interface {
	VisitPostGardensResponse(w http.ResponseWriter) error
}

type PostGardens200JSONResponse Garden

func (response PostGardens200JSONResponse) VisitPostGardensResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGardensIdPlantsRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetGardensIdPlantsResponseObject interface {
	VisitGetGardensIdPlantsResponse(w http.ResponseWriter) error
}

type GetGardensIdPlants200JSONResponse []Plant

func (response GetGardensIdPlants200JSONResponse) VisitGetGardensIdPlantsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGardensIdPlants404Response struct {
}

func (response GetGardensIdPlants404Response) VisitGetGardensIdPlantsResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetGardensIdPlants500Response struct {
}

func (response GetGardensIdPlants500Response) VisitGetGardensIdPlantsResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PostGardensIdPlantsRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *PostGardensIdPlantsJSONRequestBody
}

type PostGardensIdPlantsResponseObject interface {
	VisitPostGardensIdPlantsResponse(w http.ResponseWriter) error
}

type PostGardensIdPlants200JSONResponse []Plant

func (response PostGardensIdPlants200JSONResponse) VisitPostGardensIdPlantsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostGardensIdPlants404Response struct {
}

func (response PostGardensIdPlants404Response) VisitPostGardensIdPlantsResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PostGardensIdPlants500Response struct {
}

func (response PostGardensIdPlants500Response) VisitPostGardensIdPlantsResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetGardensIdSensorsRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetGardensIdSensorsResponseObject interface {
	VisitGetGardensIdSensorsResponse(w http.ResponseWriter) error
}

type GetGardensIdSensors200JSONResponse Sensors

func (response GetGardensIdSensors200JSONResponse) VisitGetGardensIdSensorsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGardensIdSensors404Response struct {
}

func (response GetGardensIdSensors404Response) VisitGetGardensIdSensorsResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetGardensIdSensors500Response struct {
}

func (response GetGardensIdSensors500Response) VisitGetGardensIdSensorsResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PatchGardensIdSensorsRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *PatchGardensIdSensorsJSONRequestBody
}

type PatchGardensIdSensorsResponseObject interface {
	VisitPatchGardensIdSensorsResponse(w http.ResponseWriter) error
}

type PatchGardensIdSensors200JSONResponse Sensors

func (response PatchGardensIdSensors200JSONResponse) VisitPatchGardensIdSensorsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchGardensIdSensors404Response struct {
}

func (response PatchGardensIdSensors404Response) VisitPatchGardensIdSensorsResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PatchGardensIdSensors500Response struct {
}

func (response PatchGardensIdSensors500Response) VisitPatchGardensIdSensorsResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetPlantsIdRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetPlantsIdResponseObject interface {
	VisitGetPlantsIdResponse(w http.ResponseWriter) error
}

type GetPlantsId200JSONResponse Plant

func (response GetPlantsId200JSONResponse) VisitGetPlantsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPlantsId404Response struct {
}

func (response GetPlantsId404Response) VisitGetPlantsIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetPlantsId500Response struct {
}

func (response GetPlantsId500Response) VisitGetPlantsIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type PutPlantsIdRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *PutPlantsIdJSONRequestBody
}

type PutPlantsIdResponseObject interface {
	VisitPutPlantsIdResponse(w http.ResponseWriter) error
}

type PutPlantsId200JSONResponse Plant

func (response PutPlantsId200JSONResponse) VisitPutPlantsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutPlantsId404Response struct {
}

func (response PutPlantsId404Response) VisitPutPlantsIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PutPlantsId500Response struct {
}

func (response PutPlantsId500Response) VisitPutPlantsIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /gardens)
	GetGardens(ctx context.Context, request GetGardensRequestObject) (GetGardensResponseObject, error)

	// (POST /gardens)
	PostGardens(ctx context.Context, request PostGardensRequestObject) (PostGardensResponseObject, error)

	// (GET /gardens/{id}/plants)
	GetGardensIdPlants(ctx context.Context, request GetGardensIdPlantsRequestObject) (GetGardensIdPlantsResponseObject, error)

	// (POST /gardens/{id}/plants)
	PostGardensIdPlants(ctx context.Context, request PostGardensIdPlantsRequestObject) (PostGardensIdPlantsResponseObject, error)

	// (GET /gardens/{id}/sensors)
	GetGardensIdSensors(ctx context.Context, request GetGardensIdSensorsRequestObject) (GetGardensIdSensorsResponseObject, error)

	// (PATCH /gardens/{id}/sensors)
	PatchGardensIdSensors(ctx context.Context, request PatchGardensIdSensorsRequestObject) (PatchGardensIdSensorsResponseObject, error)

	// (GET /plants/{id})
	GetPlantsId(ctx context.Context, request GetPlantsIdRequestObject) (GetPlantsIdResponseObject, error)

	// (PUT /plants/{id})
	PutPlantsId(ctx context.Context, request PutPlantsIdRequestObject) (PutPlantsIdResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetGardens operation middleware
func (sh *strictHandler) GetGardens(w http.ResponseWriter, r *http.Request) {
	var request GetGardensRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGardens(ctx, request.(GetGardensRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGardens")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGardensResponseObject); ok {
		if err := validResponse.VisitGetGardensResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostGardens operation middleware
func (sh *strictHandler) PostGardens(w http.ResponseWriter, r *http.Request) {
	var request PostGardensRequestObject

	var body PostGardensJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostGardens(ctx, request.(PostGardensRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostGardens")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostGardensResponseObject); ok {
		if err := validResponse.VisitPostGardensResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGardensIdPlants operation middleware
func (sh *strictHandler) GetGardensIdPlants(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetGardensIdPlantsRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGardensIdPlants(ctx, request.(GetGardensIdPlantsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGardensIdPlants")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGardensIdPlantsResponseObject); ok {
		if err := validResponse.VisitGetGardensIdPlantsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostGardensIdPlants operation middleware
func (sh *strictHandler) PostGardensIdPlants(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request PostGardensIdPlantsRequestObject

	request.Id = id

	var body PostGardensIdPlantsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostGardensIdPlants(ctx, request.(PostGardensIdPlantsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostGardensIdPlants")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostGardensIdPlantsResponseObject); ok {
		if err := validResponse.VisitPostGardensIdPlantsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGardensIdSensors operation middleware
func (sh *strictHandler) GetGardensIdSensors(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetGardensIdSensorsRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGardensIdSensors(ctx, request.(GetGardensIdSensorsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGardensIdSensors")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGardensIdSensorsResponseObject); ok {
		if err := validResponse.VisitGetGardensIdSensorsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchGardensIdSensors operation middleware
func (sh *strictHandler) PatchGardensIdSensors(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request PatchGardensIdSensorsRequestObject

	request.Id = id

	var body PatchGardensIdSensorsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchGardensIdSensors(ctx, request.(PatchGardensIdSensorsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchGardensIdSensors")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchGardensIdSensorsResponseObject); ok {
		if err := validResponse.VisitPatchGardensIdSensorsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPlantsId operation middleware
func (sh *strictHandler) GetPlantsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetPlantsIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPlantsId(ctx, request.(GetPlantsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPlantsId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPlantsIdResponseObject); ok {
		if err := validResponse.VisitGetPlantsIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutPlantsId operation middleware
func (sh *strictHandler) PutPlantsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request PutPlantsIdRequestObject

	request.Id = id

	var body PutPlantsIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutPlantsId(ctx, request.(PutPlantsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutPlantsId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutPlantsIdResponseObject); ok {
		if err := validResponse.VisitPutPlantsIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RWwWrcMBD9lWXao1m7bXqIjqUQlkIbKD2FEFRrNqtgS8poHAhB/14keZt17DROuwlp",
	"e9k10lh67817g2+gtq2zBg17EDfg6w22Mj2eS1Jo4pMj65BYY1rXKv6uLbWSQUDXaQUF8LVDEOCZtDmH",
	"UIBu5TmeddTE6tGukS1ObIQCCC87TahAnEA6OZWehqIHdFYTSsYxrnlH/jzNNdLw+JS1rNlvEPlsLs9n",
	"lmMAsLjD515xHk9rD3jvg+rReEsJl1RKs7ZGNscDvKMb+wX7/QJrhhCv0mZtU63mJu5980gLJVkuPNKV",
	"rhEKuELy2hoQUC3fLKt4knVopNMg4N2yWlZQgJO8SbeW2WLZ/pjcEUHJiHClQMAR8lFfEql6Z43PgN9W",
	"VfyrrWHMvpLONbpO75YX3prbeKUUMbbpxdeEaxDwqrwNYtmnsIezQ18SyevMXqGvSTvO7L58ilXvM4jh",
	"1sowkpFNUgVpgUSW8hnO+gmSx9YPWF526PmDVdePIvgwr61ZQ8jG+QM154g4LVpa3va9vNEqlClJczyw",
	"Use59Dm8kOfVbCscVAdjK3y2vFjbzqjfMosk2SJjDO7J3feyIovVR4i5BJEytc28yJPrdjQwdVjsCPDA",
	"NAqnM6w6aMb+LTsYr3tw7N/Q81Eydgb3g9H42tc+YbK3cP6fEEiuNxMpiMuTwu8/Bzuah3+ptdHrefAn",
	"q//K4nnOrNRTWrtP/gsxdmL8lL7upmZ7N1T65c/0F9TQkD6z41ruZ/qQhw2zE2XZ2Fo2G+tZHFaHFYTT",
	"8CMAAP//r4KrxgcOAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
