openapi: 3.0.0
info:
  title: Plant facts service
  version: 0.1.0
servers:
  - url: http://localhost:8080
paths:
  /facts:
    get:
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/plant_requirements"
        "500":
          description: "Internal server error"
  /facts/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          description: plant ID
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/plant"
        "404":
          description: "Not found"
        "500":
          description: "Internal server error"
  /requirements/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/requirements"
        "404":
          description: "Not found"
        "500":
          description: "Internal server error"
  /search:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/search_request"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/plant"
        "400":
          description: "Bad request - invalid query"
        "500":
          description: "Internal server error"
components:
  schemas:
    plant:
      properties:
        id:
          type: string
          format: uuid
        common_name:
          type: string
        scientific_name:
          type: string
      required:
        - id
        - common_name
        - scientific_name
    plant_requirements:
      properties:
        plant:
          $ref: "#/components/schemas/plant"
        requirements:
          $ref: "#/components/schemas/requirements"
      required:
        - plant
        - requirements
    requirements:
      properties:
        temperature:
          $ref: "#/components/schemas/requirement"
        soil_moisture:
          $ref: "#/components/schemas/requirement"
        light_intensity:
          $ref: "#/components/schemas/requirement"
      required:
        - temperature
        - soil_moisture
        - light_intensity
    requirement:
      properties:
        min:
          type: number
          format: double
        max:
          type: number
          format: double
        unit:
          type: string
      required:
        - min
        - max
        - unit
    search_request:
      properties:
        name:
          type: string
